#!/bin/bash

echo "==================================="
echo "Feature Flag Manager - Comandos"
echo "==================================="
echo ""
echo "🚀 Build e Inicialização:"
echo "  ./build.sh         - Builda as imagens Docker"
echo "  ./up.sh            - Sobe o ambiente (LocalStack + Lambda)"
echo "  ./down.sh          - Para o ambiente"
echo "  ./restart.sh       - Reinicia o ambiente"
echo ""
echo "📋 Logs e Debug:"
echo "  ./logs.sh          - Mostra logs do LocalStack"
echo "  ./logs-lambda.sh   - Mostra logs da Lambda"
echo "  ./info.sh          - Mostra informações do ambiente"
echo ""
echo "🧪 Testes:"
echo "  ./test-api.sh      - Testa a API (curl)"
echo "  ./test-python.sh   - Testa a API (Python completo)"
echo "  ./validate.sh      - Valida o ambiente"
echo ""
echo "🧹 Limpeza:"
echo "  ./clean.sh         - Remove tudo (containers, volumes, dados)"
echo ""
echo "🌐 Swagger UI:"
echo "  ./swagger-ui.sh    - Inicia servidor web para Swagger UI (porta 8080)"
echo "  ./test-swagger.sh  - Testa o Swagger UI"
echo ""
echo "📚 Documentação:"
echo "  cat GETTING_STARTED.md    - Guia de 5 minutos"
echo "  cat QUICK_REFERENCE.md    - Referência rápida"
echo "  cat LOCAL_DEVELOPMENT.md  - Guia completo"
echo "  cat SWAGGER_GUIDE.md      - Como usar o Swagger UI"
echo ""
echo "==================================="
echo ""
echo "💡 Dica: Execute './swagger-ui.sh' e acesse http://localhost:8080"
echo ""
